var std_grid ={
	"0":{
		"0":{"team":"a", "type":types.tank, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"b", "type":types.troops, "selected":false}
	},
	"1":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"2":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"3":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"4":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"5":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"6":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"7":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"8":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
	"9":{
		"0":{"team":"0", "type":types.clear, "selected":false},
		"1":{"team":"0", "type":types.clear, "selected":false},
		"2":{"team":"0", "type":types.clear, "selected":false},
		"3":{"team":"0", "type":types.clear, "selected":false},
		"4":{"team":"0", "type":types.clear, "selected":false},
		"5":{"team":"0", "type":types.clear, "selected":false},
		"6":{"team":"0", "type":types.clear, "selected":false},
		"7":{"team":"0", "type":types.clear, "selected":false},
		"8":{"team":"0", "type":types.clear, "selected":false},
		"9":{"team":"0", "type":types.clear, "selected":false}
	},
};